"""Custom exception classes for PrimeTrade AI.

Defines a hierarchy of domain-specific exceptions to enable clean try-except blocks,
contextual error reporting, and robust recovery paths.
"""


class ProjectError(Exception):
    """Base exception class for all errors generated by PrimeTrade AI."""

    def __init__(self, message: str, details: dict | None = None) -> None:
        """Initializes the base exception.

        Args:
            message: A descriptive error message.
            details: Optional dictionary containing error metadata.
        """
        super().__init__(message)
        self.message = message
        self.details = details or {}


class DatasetError(ProjectError):
    """Raised when dataset loading, ingestion, formatting, or validation fails."""


class ValidationError(ProjectError):
    """Raised when data values, trade limits, or structural rules are violated."""


class ConfigurationError(ProjectError):
    """Raised when environment variables or system settings are missing or invalid."""


class TradingBotError(ProjectError):
    """Base exception for all trading bot execution errors."""


class AnalyticsError(ProjectError):
    """Raised when statistical analysis, visualization, or report generation fails."""


class NetworkError(ProjectError):
    """Raised when network requests or websockets drop/fail."""


class APIError(TradingBotError):
    """Raised when external exchange APIs return error codes or bad responses."""

    def __init__(
        self, message: str, status_code: int | None = None, details: dict | None = None
    ) -> None:
        """Initializes the API error.

        Args:
            message: A descriptive error message.
            status_code: Optional HTTP status code returned by the server.
            details: Optional dictionary containing exchange response payload.
        """
        super().__init__(message, details)
        self.status_code = status_code
