"""PDF report compilation module for PrimeTrade AI.

Generates high-fidelity PDF reports using the fpdf2 library.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from fpdf import FPDF

from config.paths import CHARTS_OUTPUT_DIR, REPORTS_OUTPUT_DIR
from utils.logger import analytics_logger


class PrimeTradePDF(FPDF):
    """Custom FPDF subclass adding styling, headers, and footers."""

    def __init__(self, report_title: str, report_type: str, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
        self.report_title = report_title
        self.report_type = report_type
        self.alias_nb_pages()

    def header(self) -> None:
        """Draws page header on all pages after the first cover page."""
        if self.page_no() == 1:
            return  # Skip header on cover page

        # Drawing a premium header
        self.set_text_color(148, 163, 184)  # Slate gray text
        self.set_font("helvetica", "B", 8)
        self.cell(
            0,
            10,
            f"PRIMETRADE AI - {self.report_type.upper()}",
            border=0,
            align="L",
        )
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, "STRICTLY CONFIDENTIAL", border=0, align="R")
        self.ln(8)

        # Subtle divider line
        self.set_draw_color(51, 65, 85)  # Slate border
        self.set_line_width(0.3)
        self.line(10, 18, 200, 18)
        self.ln(4)

    def footer(self) -> None:
        """Draws page footer on all pages after the first cover page."""
        if self.page_no() == 1:
            return  # Skip footer on cover page

        self.set_y(-15)
        # Subtle divider line above footer
        self.set_draw_color(51, 65, 85)
        self.set_line_width(0.3)
        self.line(10, self.get_y() - 2, 200, self.get_y() - 2)

        self.set_text_color(148, 163, 184)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", border=0, align="C")

        # Right aligned document state
        self.set_font("helvetica", "", 7)
        self.cell(0, 10, "Generated by PrimeTrade AI Engine", border=0, align="R")

    def draw_cover_page(self) -> None:
        """Draws a premium portfolio cover page for the report."""
        self.add_page()
        # Set dark background for cover page
        self.set_fill_color(11, 15, 25)  # #0b0f19
        self.rect(0, 0, 210, 297, "F")

        # Header branding
        self.set_y(50)
        self.set_text_color(59, 130, 246)  # #3b82f6 Primary Blue
        self.set_font("helvetica", "B", 14)
        self.cell(0, 10, "PRIMETRADE AI SYSTEMS", border=0, align="C", ln=True)
        self.ln(10)

        # Title
        self.set_text_color(248, 250, 252)  # #f8fafc Main text
        self.set_font("helvetica", "B", 24)
        self.multi_cell(0, 15, self.report_title.upper(), border=0, align="C")
        self.ln(5)

        # Divider line
        self.set_draw_color(139, 92, 246)  # #8b5cf6 Accent Purple
        self.set_line_width(1.5)
        self.line(40, self.get_y(), 170, self.get_y())
        self.ln(12)

        # Subtitle
        self.set_text_color(148, 163, 184)  # #94a3b8 Muted text
        self.set_font("helvetica", "I", 12)
        self.cell(0, 10, "Sentiment-Driven Trading Intelligence & Risk Analytics", border=0, align="C", ln=True)
        self.ln(80)

        # Metadata box
        self.set_y(-60)
        self.set_text_color(248, 250, 252)
        self.set_font("helvetica", "B", 9)
        self.cell(0, 6, f"REPORT TYPE: {self.report_type}", border=0, align="C", ln=True)
        self.set_font("helvetica", "", 9)
        self.cell(
            0,
            6,
            f"GENERATED: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            border=0,
            align="C",
            ln=True,
        )
        self.cell(0, 6, "STATUS: COMPLETED & VERIFIED", border=0, align="C", ln=True)

    def draw_heading(self, text: str, level: int = 1) -> None:
        """Draws a clean section heading."""
        if level == 1:
            self.ln(6)
            self.set_text_color(248, 250, 252)  # White
            self.set_font("helvetica", "B", 14)
            # Left accent bar
            self.set_fill_color(59, 130, 246)  # Accent primary blue
            self.rect(self.get_x(), self.get_y() + 1, 3, 6, "F")
            self.set_x(self.get_x() + 5)
            self.cell(0, 8, text, border=0, ln=True)
            self.ln(4)
        else:
            self.ln(4)
            self.set_text_color(248, 250, 252)
            self.set_font("helvetica", "B", 11)
            self.cell(0, 6, text, border=0, ln=True)
            self.ln(3)

    def draw_text(self, text: str, style: str = "") -> None:
        """Draws body text with multi-page line wrapping."""
        self.set_text_color(148, 163, 184)  # Slate text
        if style == "bold":
            self.set_font("helvetica", "B", 9)
        elif style == "italic":
            self.set_font("helvetica", "I", 9)
        else:
            self.set_font("helvetica", "", 9)
        self.multi_cell(0, 5, text)
        self.ln(3)

    def draw_bullet(self, text: str, label: str = "") -> None:
        """Draws a bullet list item."""
        self.set_text_color(59, 130, 246)  # Accent blue bullet
        self.set_font("helvetica", "B", 9)
        self.write(5, "  * ")
        if label:
            self.set_text_color(248, 250, 252)
            self.set_font("helvetica", "B", 9)
            self.write(5, f"{label}: ")
        self.set_text_color(148, 163, 184)
        self.set_font("helvetica", "", 9)
        self.write(5, f"{text}\n")
        self.ln(2)

    def draw_table_headers(self, col_names: list, col_widths: list) -> None:
        """Draws table header row."""
        self.set_fill_color(30, 41, 59)  # #1e293b
        self.set_text_color(248, 250, 252)  # #f8fafc
        self.set_font("helvetica", "B", 8)
        for name, width in zip(col_names, col_widths):
            self.cell(width, 7, name, border=1, fill=True, align="L")
        self.ln()

    def draw_table_row(
        self, row_values: list, col_widths: list, is_profit_col_idx: int = -1, is_loss_col_idx: int = -1
    ) -> None:
        """Draws a table row with custom highlight values."""
        self.set_fill_color(19, 26, 44)  # #131a2c
        self.set_font("helvetica", "", 8)
        for idx, (val, width) in enumerate(zip(row_values, col_widths)):
            # Set colors for specific columns
            if idx == is_profit_col_idx:
                self.set_text_color(34, 197, 94)  # Green
            elif idx == is_loss_col_idx:
                self.set_text_color(239, 104, 104)  # Red
            else:
                self.set_text_color(148, 163, 184)  # Gray
            self.cell(width, 6, str(val), border=1, fill=True, align="L")
        self.ln()

    def draw_chart(self, filename: str, caption: str) -> None:
        """Embeds a static PNG chart from the charts directory."""
        chart_path = CHARTS_OUTPUT_DIR / filename
        if chart_path.exists():
            self.ln(4)
            # Center image
            x_pos = (210 - 150) / 2
            try:
                self.image(str(chart_path), x=x_pos, w=150, h=85)
                self.ln(2)
                self.set_text_color(148, 163, 184)
                self.set_font("helvetica", "I", 7)
                self.cell(0, 4, caption, border=0, align="C", ln=True)
                self.ln(4)
            except Exception as e:
                analytics_logger.error(f"Failed to render image in PDF: {e}")
                self.draw_box_message(f"Chart Render Error: {filename}")
        else:
            self.draw_box_message(f"Chart Not Found: {filename}")

    def draw_box_message(self, message: str, level: str = "info") -> None:
        """Draws a warning or info callout box."""
        self.ln(3)
        if level == "warning":
            self.set_fill_color(69, 26, 3)  # Dark warning red/orange background
            self.set_draw_color(245, 158, 11)  # Orange border
            self.set_text_color(254, 243, 199)  # Light orange text
        else:
            self.set_fill_color(30, 41, 59)  # Dark slate info background
            self.set_draw_color(59, 130, 246)  # Blue border
            self.set_text_color(248, 250, 252)

        self.set_line_width(0.5)
        # Rect with fill and border
        self.rect(10, self.get_y(), 190, 12, "FD")
        self.set_x(14)
        self.set_font("helvetica", "B", 8)
        self.cell(0, 12, message, border=0, align="L", ln=True)
        self.ln(4)


class PDFReportCompiler:
    """Compiles structured trading intelligence reports into high-fidelity PDF documents."""

    @classmethod
    def _format_pct(cls, val: Any) -> str:
        """Helper to format percentage."""
        try:
            if val is None:
                return "N/A"
            return f"{float(val) * 100:.2f}%"
        except (ValueError, TypeError):
            return str(val)

    @classmethod
    def _format_currency(cls, val: Any) -> str:
        """Helper to format currency."""
        try:
            if val is None:
                return "N/A"
            v = float(val)
            sign = "-" if v < 0 else ""
            return f"{sign}${abs(v):,.2f}"
        except (ValueError, TypeError):
            return str(val)

    @classmethod
    def _format_float(cls, val: Any, decimal_places: int = 4) -> str:
        """Helper to format float values."""
        try:
            if val is None:
                return "N/A"
            return f"{float(val):.{decimal_places}f}"
        except (ValueError, TypeError):
            return str(val)

    @classmethod
    def compile_executive_summary(cls, analytics_res: Dict[str, Any], statistics_res: Dict[str, Any]) -> PrimeTradePDF:
        """Compiles the PDF Executive Summary."""
        pdf = PrimeTradePDF(
            report_title="Executive Performance Summary",
            report_type="Executive Report",
        )
        pdf.draw_cover_page()

        # Page 2: Table of Contents & Overview
        pdf.add_page()
        pdf.set_fill_color(11, 15, 25)  # Dark background color for content pages
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("1. Document Overview")
        pdf.draw_text(
            "This document summarizes portfolio performance, sentiment regime dynamics, and "
            "recommendations calculated by the PrimeTrade AI engine based on trader execution records."
        )

        perf = analytics_res.get("performance_analysis", {})
        risk = analytics_res.get("risk_analysis", {})
        sentiment = analytics_res.get("sentiment_analysis", {})
        coin = analytics_res.get("coin_analysis", {})
        intel = analytics_res.get("intelligence_summary", {})

        # Warnings block
        warnings = intel.get("warnings", [])
        if warnings:
            pdf.draw_heading("Active System Alerts", level=2)
            for warn in warnings:
                pdf.draw_box_message(warn, level="warning")

        # KPI Metrics Table
        pdf.draw_heading("2. Key Performance Indicators")
        headers = ["KPI Metric Parameter", "Value", "Description"]
        widths = [60, 40, 90]
        pdf.draw_table_headers(headers, widths)

        # Net profit color index
        net_profit = perf.get("net_profit", 0)
        net_profit_str = cls._format_currency(net_profit)

        kpis = [
            ["Total Executed Trades", str(perf.get("total_trades", 0)), "Number of completed futures contracts"],
            ["Net Realized Profit/Loss", net_profit_str, "Combined trading outcomes"],
            ["Global Win Rate", cls._format_pct(perf.get("win_rate", 0)), "Proportion of winning contracts"],
            ["Profit Factor", cls._format_float(perf.get("profit_factor", 0), 2), "Profit to loss ratio"],
            ["Average PnL per Trade", cls._format_currency(perf.get("average_pnl", 0)), "Mean trade profitability"],
            ["Portfolio Sharpe Ratio", cls._format_float(perf.get("sharpe_ratio", 0), 2), "Risk-adjusted performance rating"],
            ["Maximum Drawdown", cls._format_pct(risk.get("max_drawdown", 0)), "Peak-to-trough return decline"],
            [
                "Composite Risk Score",
                f"{cls._format_float(risk.get('composite_risk_score', 0), 2)} / 10",
                "Aggregated risk valuation",
            ],
        ]

        for kpi in kpis:
            # Highlight Profit/Loss in the second row
            if kpi[0] == "Net Realized Profit/Loss":
                if net_profit >= 0:
                    pdf.draw_table_row(kpi, widths, is_profit_col_idx=1)
                else:
                    pdf.draw_table_row(kpi, widths, is_loss_col_idx=1)
            else:
                pdf.draw_table_row(kpi, widths)

        # Page 3: Sentiment & Assets
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("3. Sentiment Regime Mappings")
        pdf.draw_text(
            f"The system processed {sentiment.get('sentiment_regime_count', {}).get('Total', 0)} data mappings "
            f"against the Bitcoin Fear & Greed Index."
        )

        regimes = sentiment.get("pnl_by_sentiment_regime", {})
        if regimes:
            reg_headers = ["Sentiment Regime", "Trades Count", "Net realized PnL", "Win Rate", "Average PnL"]
            reg_widths = [45, 30, 45, 30, 40]
            pdf.draw_table_headers(reg_headers, reg_widths)

            for regime, details in regimes.items():
                if regime == "Unknown":
                    continue
                pnl = details.get("sum", 0)
                row_vals = [
                    regime,
                    str(details.get("count", 0)),
                    cls._format_currency(pnl),
                    cls._format_pct(details.get("win_rate", 0)),
                    cls._format_currency(details.get("mean", 0)),
                ]
                if pnl >= 0:
                    pdf.draw_table_row(row_vals, reg_widths, is_profit_col_idx=2)
                else:
                    pdf.draw_table_row(row_vals, reg_widths, is_loss_col_idx=2)

        # Recommendations list
        pdf.draw_heading("4. Strategic Optimization Guidelines")
        recs = intel.get("recommendations", [])
        for rec in recs:
            pdf.draw_bullet(rec)

        # Page 4: Charts
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")
        pdf.draw_heading("5. Visual Analytics Appendix")

        pdf.draw_chart(
            "cumulative_pnl.png",
            "Figure 1.1: Cumulative Realized Portfolio Performance (Matplotlib PNG)",
        )
        pdf.draw_chart(
            "win_loss_pie.png",
            "Figure 1.2: Trades Win vs. Loss Ratio Breakdown (Matplotlib PNG)",
        )

        return pdf

    @classmethod
    def compile_technical_summary(cls, analytics_res: Dict[str, Any], statistics_res: Dict[str, Any]) -> PrimeTradePDF:
        """Compiles the PDF Technical & Statistical Report."""
        pdf = PrimeTradePDF(
            report_title="Technical & Statistical Report",
            report_type="Technical Report",
        )
        pdf.draw_cover_page()

        descriptive = statistics_res.get("descriptive", {})
        corr = statistics_res.get("correlations", {})
        hypo = statistics_res.get("hypothesis_tests", {})
        dist = statistics_res.get("distributions", {})
        ci = statistics_res.get("confidence_intervals", {})
        effects = statistics_res.get("effect_sizes", {})
        obs = statistics_res.get("observations", [])

        # Page 2: Stats
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("1. Descriptive Parameter Scope")
        pdf.draw_text(
            "Central tendency, shape, and variance statistics calculated on closed PnL " "and market volatility features."
        )

        pnl_stats = descriptive.get("closed_pnl", {})
        vol_stats = descriptive.get("market_volatility", {})

        desc_headers = ["Parameter", "Realized Closed PnL Value", "Market Volatility Index"]
        desc_widths = [60, 65, 65]
        pdf.draw_table_headers(desc_headers, desc_widths)

        parameters = [
            ["Sample Mean", cls._format_currency(pnl_stats.get("mean")), cls._format_float(vol_stats.get("mean"))],
            ["Standard Deviation", cls._format_float(pnl_stats.get("std")), cls._format_float(vol_stats.get("std"))],
            ["Distribution Skewness", cls._format_float(pnl_stats.get("skew")), cls._format_float(vol_stats.get("skew"))],
            [
                "Distribution Kurtosis",
                cls._format_float(pnl_stats.get("kurtosis")),
                cls._format_float(vol_stats.get("kurtosis")),
            ],
            ["Minimum Realized Value", cls._format_currency(pnl_stats.get("min")), cls._format_float(vol_stats.get("min"))],
            ["Median (50th Percentile)", cls._format_currency(pnl_stats.get("50%")), cls._format_float(vol_stats.get("50%"))],
            ["Maximum Realized Value", cls._format_currency(pnl_stats.get("max")), cls._format_float(vol_stats.get("max"))],
        ]
        for row in parameters:
            pdf.draw_table_row(row, desc_widths)

        pdf.draw_heading("2. Sentiment Correlation Mappings")
        corr_headers = ["Variable Pair Relationship", "Pearson Coeff", "Pearson p-val", "Spearman Coeff", "Sig?"]
        corr_widths = [65, 30, 30, 35, 30]
        pdf.draw_table_headers(corr_headers, corr_widths)

        for key, value in corr.items():
            if isinstance(value, dict) and "pearson" in value and "spearman" in value:
                p_coef = value["pearson"].get("coefficient")
                p_pval = value["pearson"].get("p_value")
                s_coef = value["spearman"].get("coefficient")
                sig = "YES" if value["pearson"].get("significant") or value["spearman"].get("significant") else "NO"
                row_vals = [
                    key.replace("_", " ").title(),
                    cls._format_float(p_coef),
                    cls._format_float(p_pval),
                    cls._format_float(s_coef),
                    sig,
                ]
                if sig == "YES":
                    pdf.draw_table_row(row_vals, corr_widths, is_profit_col_idx=4)
                else:
                    pdf.draw_table_row(row_vals, corr_widths)

        # Page 3: Hypothesis testing & intervals
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("3. Hypothesis Verification Suite")
        hypo_headers = ["Test Method", "Statistic", "p-value", "Significant?", "Target Description"]
        hypo_widths = [45, 25, 25, 25, 70]
        pdf.draw_table_headers(hypo_headers, hypo_widths)

        tests_list = [
            ("t_test", "Independent T-Test", "Fear vs. Greed PnL Means"),
            ("mann_whitney", "Mann-Whitney U", "Fear vs. Greed Rank Comparison"),
            ("anova", "One-Way ANOVA", "PnL Means across all classes"),
            ("chi_square", "Chi-Square", "Sides Mappings vs. Regimes"),
        ]

        for key, name, desc in tests_list:
            t = hypo.get(key, {})
            if t:
                sig = "YES" if t.get("significant") else "NO"
                row_vals = [
                    name,
                    cls._format_float(t.get("stat")),
                    cls._format_float(t.get("p_value")),
                    sig,
                    desc,
                ]
                if sig == "YES":
                    pdf.draw_table_row(row_vals, hypo_widths, is_profit_col_idx=3)
                else:
                    pdf.draw_table_row(row_vals, hypo_widths)

        # Normality and Confidence Intervals
        pdf.draw_heading("4. Parameter Confidence Bands (95% Confidence)")
        ci_headers = ["Parameter Title", "Sample Est", "CI Lower", "CI Upper", "Interval Type"]
        ci_widths = [55, 30, 30, 35, 40]
        pdf.draw_table_headers(ci_headers, ci_widths)

        for param, details in ci.items():
            if isinstance(details, dict):
                name = param.replace("_", " ").title()
                est = details.get("estimate")
                low = details.get("lower_bound")
                up = details.get("upper_bound")
                ci_type = details.get("type", "Student-t")
                if "win_rate" in param:
                    row_vals = [name, cls._format_pct(est), cls._format_pct(low), cls._format_pct(up), "Wilson Score"]
                else:
                    row_vals = [name, cls._format_currency(est), cls._format_currency(low), cls._format_currency(up), ci_type]
                pdf.draw_table_row(row_vals, ci_widths)

        # Page 4: Effect Sizes & Charts
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("5. Statistical Effect Sizes")
        cohen = effects.get("cohens_d", {})
        eta = effects.get("eta_squared", {})
        pdf.draw_bullet(
            f"{cls._format_float(cohen.get('value'))} ({cohen.get('interpretation', 'N/A')})",
            label="Cohen's d (Fear vs Greed PnLs)",
        )
        pdf.draw_bullet(
            f"{cls._format_float(eta.get('value'))} ({eta.get('interpretation', 'N/A')})",
            label="Eta-squared (ANOVA Regime Variance)",
        )

        pdf.draw_heading("6. Mathematical Observations")
        for ob in obs[:6]:  # Limit observations to fit on page
            pdf.draw_bullet(ob)

        # Page 5: Charts
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")
        pdf.draw_heading("7. Statistical Charts Appendix")

        pdf.draw_chart(
            "pnl_distribution.png",
            "Figure 2.1: Portfolio realized returns fit with a Kernel Density Estimate.",
        )
        pdf.draw_chart(
            "sentiment_correlation_scatter.png",
            "Figure 2.2: Fear & Greed sentiment values vs Realized returns featuring OLS trend line.",
        )

        return pdf

    @classmethod
    def compile_business_report(cls, analytics_res: Dict[str, Any], statistics_res: Dict[str, Any]) -> PrimeTradePDF:
        """Compiles the PDF Business Report."""
        pdf = PrimeTradePDF(
            report_title="Portfolio & Business Performance",
            report_type="Business Report",
        )
        pdf.draw_cover_page()

        perf = analytics_res.get("performance_analysis", {})
        risk = analytics_res.get("risk_analysis", {})
        traders = analytics_res.get("trader_analysis", {})
        coin = analytics_res.get("coin_analysis", {})
        time_analysis = analytics_res.get("time_analysis", {})
        intel = analytics_res.get("intelligence_summary", {})

        # Page 2: Portfolio Profitability & Risk
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("1. Portfolio Profitability Summary")
        prof_headers = ["Performance Metric Parameter", "Value", "Business Definition"]
        prof_widths = [65, 40, 85]
        pdf.draw_table_headers(prof_headers, prof_widths)

        net_profit = perf.get("net_profit", 0)
        net_profit_str = cls._format_currency(net_profit)

        prof_rows = [
            ["Gross Realized Profit", cls._format_currency(perf.get("gross_profit", 0)), "Sum of winning trades"],
            ["Gross Realized Loss", cls._format_currency(perf.get("gross_loss", 0)), "Sum of losing trades"],
            ["Net Realized Return", net_profit_str, "Combined net trading outcomes"],
            ["Trading Win Rate", cls._format_pct(perf.get("win_rate", 0)), "Percent of profitable contracts"],
            ["Profit Factor ratio", cls._format_float(perf.get("profit_factor", 0), 2), "Profits divided by losses"],
            ["Trading Brokerage Fees", cls._format_currency(perf.get("total_fees", 0)), "Binance Futures commission charges"],
        ]

        for row in prof_rows:
            if row[0] == "Net Realized Return":
                if net_profit >= 0:
                    pdf.draw_table_row(row, prof_widths, is_profit_col_idx=1)
                else:
                    pdf.draw_table_row(row, prof_widths, is_loss_col_idx=1)
            else:
                pdf.draw_table_row(row, prof_widths)

        pdf.draw_heading("2. Portfolio Risk Exposures")
        risk_headers = ["Risk Metric Parameter", "Value", "Business Definition"]
        risk_widths = [65, 40, 85]
        pdf.draw_table_headers(risk_headers, risk_widths)

        risk_rows = [
            [
                "Portfolio Volatility (Std PnL)",
                cls._format_float(risk.get("pnl_volatility", 0), 4),
                "Realized returns standard deviation",
            ],
            ["Maximum Drawdown", cls._format_pct(risk.get("max_drawdown", 0)), "Peak-to-trough decline in returns"],
            [
                "Value at Risk (95% VaR)",
                cls._format_currency(risk.get("value_at_risk_95", 0)),
                "Estimated maximum loss at 95% confidence",
            ],
            [
                "Expected Shortfall (95% ES)",
                cls._format_currency(risk.get("expected_shortfall_95", 0)),
                "Average loss in worst 5% tail scenario",
            ],
            [
                "Average Win/Loss Size Ratio",
                cls._format_float(risk.get("profit_loss_ratio", 0), 2),
                "Average win divided by average loss",
            ],
            ["Composite Risk State", risk.get("risk_classification", "Unknown"), "Overall risk condition rating"],
        ]

        for row in risk_rows:
            if row[0] == "Composite Risk State":
                classification = risk.get("risk_classification", "Unknown")
                if classification in ["High Risk", "Extreme Risk"]:
                    pdf.draw_table_row(row, risk_widths, is_loss_col_idx=1)
                else:
                    pdf.draw_table_row(row, risk_widths, is_profit_col_idx=1)
            else:
                pdf.draw_table_row(row, risk_widths)

        # Page 3: Asset Profitability Leaderboard & Trader Rankings
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("3. Asset Profitability Leaderboard")
        coin_headers = ["Asset Symbol", "Net realized Return", "Trades Count", "Win Rate", "Volume Size"]
        coin_widths = [35, 45, 30, 35, 45]
        pdf.draw_table_headers(coin_headers, coin_widths)

        coin_pnls = coin.get("coin_pnls", {})
        if coin_pnls:
            sorted_coins = sorted(coin_pnls.items(), key=lambda item: item[1].get("sum", 0), reverse=True)
            for symbol, details in sorted_coins[:10]:
                pnl = details.get("sum", 0)
                row_vals = [
                    symbol,
                    cls._format_currency(pnl),
                    str(details.get("count", 0)),
                    cls._format_pct(details.get("win_rate", 0)),
                    cls._format_float(details.get("volume", 0), 2),
                ]
                if pnl >= 0:
                    pdf.draw_table_row(row_vals, coin_widths, is_profit_col_idx=1)
                else:
                    pdf.draw_table_row(row_vals, coin_widths, is_loss_col_idx=1)

        pdf.draw_heading("4. Trader Performance Rankings")
        trader_headers = ["Account Code", "Net Realized PnL", "Win Rate", "Profit Factor", "Trades"]
        trader_widths = [50, 40, 35, 35, 30]
        pdf.draw_table_headers(trader_headers, trader_widths)

        top_traders = traders.get("top_10_traders", [])
        for idx, t in enumerate(top_traders[:5], 1):  # Top 5 to fit page
            row_vals = [
                f"Rank #{idx} {t.get('trader_id')}",
                cls._format_currency(t.get("net_profit")),
                cls._format_pct(t.get("win_rate")),
                cls._format_float(t.get("profit_factor"), 2),
                str(t.get("total_trades")),
            ]
            pdf.draw_table_row(row_vals, trader_widths, is_profit_col_idx=1)

        # Page 4: Temporal analysis & recommendations
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")

        pdf.draw_heading("5. UTC Session Temporal Breakdown")
        pdf.draw_bullet(f"{time_analysis.get('best_trading_hour')}:00 UTC", label="Most Profitable Session Hour")
        pdf.draw_bullet(f"{time_analysis.get('worst_trading_hour')}:00 UTC", label="Least Profitable Session Hour")
        pdf.draw_bullet(time_analysis.get("best_trading_day"), label="Most Profitable Day of Week")
        pdf.draw_bullet(time_analysis.get("worst_trading_day"), label="Least Profitable Day of Week")

        pdf.draw_heading("6. Strategic Business Recommendations")
        recs = intel.get("recommendations", [])
        for rec in recs[:6]:
            pdf.draw_bullet(rec)

        # Page 5: Charts
        pdf.add_page()
        pdf.rect(0, 0, 210, 297, "F")
        pdf.draw_heading("7. Business Charts Appendix")

        pdf.draw_chart(
            "coin_leaderboard.png",
            "Figure 3.1: Net realized return across symbols traded (Asset Rankings).",
        )
        pdf.draw_chart(
            "hourly_heatmap.png",
            "Figure 3.2: UTC hour of day vs day of week trading performance distribution.",
        )

        return pdf

    @classmethod
    def compile_all(cls, analytics_res: Dict[str, Any], statistics_res: Dict[str, Any]) -> Dict[str, PrimeTradePDF]:
        """Compiles all three PDF reports and returns them in a dictionary."""
        return {
            "executive_summary": cls.compile_executive_summary(analytics_res, statistics_res),
            "technical_summary": cls.compile_technical_summary(analytics_res, statistics_res),
            "business_report": cls.compile_business_report(analytics_res, statistics_res),
        }
